import { Student, Teacher, Parent, Class, Attendance, Fee, Exam, Result, Transport, LibraryBook, BookIssue, Announcement, Staff, DashboardStats, TimetableEntry } from '../types';

export const mockStudents: Student[] = [
  {
    id: '1',
    admissionNumber: 'STU001',
    name: 'Arjun Kumar',
    email: 'arjun.kumar@student.school.com',
    phone: '+91 9876543210',
    dateOfBirth: '2010-05-15',
    gender: 'male',
    class: '10',
    section: 'A',
    rollNumber: '15',
    parentId: 'P001',
    parentName: 'Rajesh Kumar',
    address: '123 MG Road, Bangalore',
    admissionDate: '2020-04-01',
    bloodGroup: 'O+',
    status: 'active',
  },
  {
    id: '2',
    admissionNumber: 'STU002',
    name: 'Priya Sharma',
    email: 'priya.sharma@student.school.com',
    phone: '+91 9876543211',
    dateOfBirth: '2010-08-22',
    gender: 'female',
    class: '10',
    section: 'A',
    rollNumber: '16',
    parentId: 'P002',
    parentName: 'Amit Sharma',
    address: '456 Brigade Road, Bangalore',
    admissionDate: '2020-04-01',
    bloodGroup: 'A+',
    status: 'active',
  },
  {
    id: '3',
    admissionNumber: 'STU003',
    name: 'Rahul Verma',
    email: 'rahul.verma@student.school.com',
    phone: '+91 9876543212',
    dateOfBirth: '2011-03-10',
    gender: 'male',
    class: '9',
    section: 'B',
    rollNumber: '12',
    parentId: 'P003',
    parentName: 'Suresh Verma',
    address: '789 Koramangala, Bangalore',
    admissionDate: '2021-04-01',
    bloodGroup: 'B+',
    status: 'active',
  },
  {
    id: '4',
    admissionNumber: 'STU004',
    name: 'Ananya Reddy',
    email: 'ananya.reddy@student.school.com',
    phone: '+91 9876543213',
    dateOfBirth: '2011-11-05',
    gender: 'female',
    class: '9',
    section: 'A',
    rollNumber: '08',
    parentId: 'P004',
    parentName: 'Krishna Reddy',
    address: '321 Indiranagar, Bangalore',
    admissionDate: '2021-04-01',
    bloodGroup: 'AB+',
    status: 'active',
  },
];

export const mockTeachers: Teacher[] = [
  {
    id: 'T001',
    employeeId: 'EMP001',
    name: 'Dr. Sanjay Mehta',
    email: 'sanjay.mehta@school.com',
    phone: '+91 9876543220',
    subjects: ['Mathematics', 'Physics'],
    classes: ['10-A', '10-B', '11-A'],
    dateOfJoining: '2015-06-01',
    qualification: 'M.Sc Physics, B.Ed',
    status: 'active',
  },
  {
    id: 'T002',
    employeeId: 'EMP002',
    name: 'Mrs. Kavita Singh',
    email: 'kavita.singh@school.com',
    phone: '+91 9876543221',
    subjects: ['English', 'Social Studies'],
    classes: ['9-A', '9-B', '10-A'],
    dateOfJoining: '2016-04-15',
    qualification: 'M.A English, B.Ed',
    status: 'active',
  },
  {
    id: 'T003',
    employeeId: 'EMP003',
    name: 'Mr. Ramesh Patel',
    email: 'ramesh.patel@school.com',
    phone: '+91 9876543222',
    subjects: ['Chemistry', 'Biology'],
    classes: ['11-A', '12-A'],
    dateOfJoining: '2014-07-10',
    qualification: 'M.Sc Chemistry, B.Ed',
    status: 'active',
  },
];

export const mockClasses: Class[] = [
  { id: '1', name: '9', sections: ['A', 'B', 'C'], classTeacher: 'Mrs. Kavita Singh', students: 90 },
  { id: '2', name: '10', sections: ['A', 'B'], classTeacher: 'Dr. Sanjay Mehta', students: 60 },
  { id: '3', name: '11', sections: ['A', 'B'], classTeacher: 'Mr. Ramesh Patel', students: 55 },
  { id: '4', name: '12', sections: ['A'], classTeacher: 'Dr. Anita Kumar', students: 30 },
];

export const mockAttendance: Attendance[] = [
  { id: '1', studentId: '1', date: '2025-10-31', status: 'present', class: '10', section: 'A' },
  { id: '2', studentId: '2', date: '2025-10-31', status: 'present', class: '10', section: 'A' },
  { id: '3', studentId: '3', date: '2025-10-31', status: 'absent', class: '9', section: 'B', remarks: 'Medical leave' },
  { id: '4', studentId: '4', date: '2025-10-31', status: 'present', class: '9', section: 'A' },
];

export const mockFees: Fee[] = [
  {
    id: '1',
    studentId: '1',
    studentName: 'Arjun Kumar',
    class: '10',
    section: 'A',
    totalAmount: 45000,
    paidAmount: 45000,
    pendingAmount: 0,
    dueDate: '2025-10-31',
    status: 'paid',
    feeType: 'tuition',
    lastPaymentDate: '2025-09-15',
  },
  {
    id: '2',
    studentId: '2',
    studentName: 'Priya Sharma',
    class: '10',
    section: 'A',
    totalAmount: 45000,
    paidAmount: 30000,
    pendingAmount: 15000,
    dueDate: '2025-11-15',
    status: 'partial',
    feeType: 'tuition',
    lastPaymentDate: '2025-08-20',
  },
  {
    id: '3',
    studentId: '3',
    studentName: 'Rahul Verma',
    class: '9',
    section: 'B',
    totalAmount: 42000,
    paidAmount: 0,
    pendingAmount: 42000,
    dueDate: '2025-10-01',
    status: 'overdue',
    feeType: 'tuition',
  },
  {
    id: '4',
    studentId: '4',
    studentName: 'Ananya Reddy',
    class: '9',
    section: 'A',
    totalAmount: 42000,
    paidAmount: 42000,
    pendingAmount: 0,
    dueDate: '2025-10-31',
    status: 'paid',
    feeType: 'tuition',
    lastPaymentDate: '2025-10-10',
  },
];

export const mockExams: Exam[] = [
  {
    id: '1',
    name: 'Mid-Term Examination',
    class: '10',
    term: 'Term 1',
    startDate: '2025-11-15',
    endDate: '2025-11-25',
    subjects: [
      { name: 'Mathematics', date: '2025-11-15', maxMarks: 100, passingMarks: 35 },
      { name: 'Science', date: '2025-11-17', maxMarks: 100, passingMarks: 35 },
      { name: 'English', date: '2025-11-19', maxMarks: 100, passingMarks: 35 },
      { name: 'Social Studies', date: '2025-11-21', maxMarks: 100, passingMarks: 35 },
      { name: 'Hindi', date: '2025-11-23', maxMarks: 100, passingMarks: 35 },
    ],
  },
];

export const mockResults: Result[] = [
  {
    id: '1',
    studentId: '1',
    examId: '1',
    subjects: [
      { name: 'Mathematics', marksObtained: 92, maxMarks: 100, grade: 'A+' },
      { name: 'Science', marksObtained: 88, maxMarks: 100, grade: 'A' },
      { name: 'English', marksObtained: 85, maxMarks: 100, grade: 'A' },
      { name: 'Social Studies', marksObtained: 90, maxMarks: 100, grade: 'A+' },
      { name: 'Hindi', marksObtained: 82, maxMarks: 100, grade: 'A' },
    ],
    totalMarks: 437,
    totalMaxMarks: 500,
    percentage: 87.4,
    grade: 'A',
    rank: 2,
  },
];

export const mockTransport: Transport[] = [
  {
    id: '1',
    busNumber: 'KA-01-1234',
    routeName: 'Route 1 - MG Road',
    driverName: 'Ramesh Kumar',
    driverPhone: '+91 9876543230',
    capacity: 40,
    students: 35,
    stops: ['MG Road', 'Brigade Road', 'Koramangala', 'BTM Layout', 'School'],
    timing: '7:00 AM - 8:30 AM',
  },
  {
    id: '2',
    busNumber: 'KA-01-5678',
    routeName: 'Route 2 - Indiranagar',
    driverName: 'Suresh Reddy',
    driverPhone: '+91 9876543231',
    capacity: 40,
    students: 38,
    stops: ['Indiranagar', 'Domlur', 'HSR Layout', 'School'],
    timing: '7:15 AM - 8:30 AM',
  },
];

export const mockLibraryBooks: LibraryBook[] = [
  {
    id: '1',
    isbn: '978-0-123456-78-9',
    title: 'Introduction to Physics',
    author: 'Dr. HC Verma',
    category: 'Science',
    totalCopies: 20,
    availableCopies: 15,
    issuedCopies: 5,
  },
  {
    id: '2',
    isbn: '978-0-234567-89-0',
    title: 'Mathematics for Class 10',
    author: 'RD Sharma',
    category: 'Mathematics',
    totalCopies: 25,
    availableCopies: 18,
    issuedCopies: 7,
  },
  {
    id: '3',
    isbn: '978-0-345678-90-1',
    title: 'English Grammar',
    author: 'Wren & Martin',
    category: 'English',
    totalCopies: 30,
    availableCopies: 22,
    issuedCopies: 8,
  },
];

export const mockBookIssues: BookIssue[] = [
  {
    id: '1',
    bookId: '1',
    bookTitle: 'Introduction to Physics',
    studentId: '1',
    studentName: 'Arjun Kumar',
    issueDate: '2025-10-15',
    dueDate: '2025-10-29',
    status: 'overdue',
    fine: 10,
  },
  {
    id: '2',
    bookId: '2',
    bookTitle: 'Mathematics for Class 10',
    studentId: '2',
    studentName: 'Priya Sharma',
    issueDate: '2025-10-20',
    dueDate: '2025-11-03',
    status: 'issued',
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: '1',
    title: 'Annual Sports Day',
    content: 'The Annual Sports Day will be held on November 15, 2025. All students are requested to participate.',
    date: '2025-10-28',
    author: 'Principal',
    priority: 'high',
    targetAudience: ['student', 'parent', 'teacher'],
  },
  {
    id: '2',
    title: 'Parent-Teacher Meeting',
    content: 'PTM scheduled for November 5, 2025. Parents are requested to meet their ward\'s class teachers.',
    date: '2025-10-25',
    author: 'Admin',
    priority: 'medium',
    targetAudience: ['parent', 'teacher'],
  },
  {
    id: '3',
    title: 'Fee Payment Reminder',
    content: 'This is a reminder that the second quarter fee payment is due by November 15, 2025.',
    date: '2025-10-30',
    author: 'Accounts Department',
    priority: 'high',
    targetAudience: ['parent'],
  },
];

export const mockStaff: Staff[] = [
  {
    id: 'S001',
    employeeId: 'EMP101',
    name: 'Rajesh Nair',
    email: 'rajesh.nair@school.com',
    phone: '+91 9876543240',
    role: 'Accountant',
    department: 'Finance',
    dateOfJoining: '2018-03-15',
    salary: 35000,
    status: 'active',
  },
  {
    id: 'S002',
    employeeId: 'EMP102',
    name: 'Sunita Desai',
    email: 'sunita.desai@school.com',
    phone: '+91 9876543241',
    role: 'Librarian',
    department: 'Library',
    dateOfJoining: '2017-08-20',
    salary: 28000,
    status: 'active',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalStudents: 235,
  totalTeachers: 28,
  totalStaff: 15,
  totalRevenue: 8750000,
  pendingFees: 1250000,
  attendanceToday: 92.5,
  activeTransport: 8,
  libraryBooks: 2450,
};

export const mockTimetable: TimetableEntry[] = [
  {
    id: '1',
    subject: 'Mathematics',
    time: '8:00 AM - 9:00 AM',
    class: '10',
    section: 'A',
    teacher: 'Dr. Sanjay Mehta',
    day: 'Monday',
    room: 'Room 101',
  },
  {
    id: '2',
    subject: 'English',
    time: '9:00 AM - 10:00 AM',
    class: '10',
    section: 'A',
    teacher: 'Mrs. Kavita Singh',
    day: 'Monday',
    room: 'Room 102',
  },
  {
    id: '3',
    subject: 'Physics',
    time: '10:00 AM - 11:00 AM',
    class: '10',
    section: 'A',
    teacher: 'Dr. Sanjay Mehta',
    day: 'Monday',
    room: 'Lab 1',
  },
  {
    id: '4',
    subject: 'Chemistry',
    time: '11:30 AM - 12:30 PM',
    class: '10',
    section: 'A',
    teacher: 'Mr. Ramesh Patel',
    day: 'Monday',
    room: 'Lab 2',
  },
  {
    id: '5',
    subject: 'Physical Education',
    time: '2:00 PM - 3:00 PM',
    class: '10',
    section: 'A',
    teacher: 'Mr. Suresh Kumar',
    day: 'Monday',
    room: 'Sports Ground',
  },
];
